version: '3.8'

services:
  db:
    image: mysql:8.4
    env_file:
      - ./src/.env
    environment:
      MYSQL_ROOT_PASSWORD: rootpwd
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data
    expose:
      - "6379"
    ports:
      - 6379:6379

volumes:
  mysql-data:
  redis-data:
